### ISSUE TITLE
from rouge_score.rouge_scorer import RougeScorer ModuleNotFoundError: No module named 'rouge_score'

### ISSUE THREAD

**Issue by Fab16BSB** [DUT-Info-Montreuil/SecretarIA#15]
pip install rouge-score

**Comment by llichten29** [comment]
Je l'ai ajouter au requiment.txt il y a un certain temps

**Comment by Fab16BSB** [comment]
@llichten29 ce que j'ai dans le requirement.txt c'est 
rouge==1.0.1
et non rouge-score
