### ISSUE TITLE
FileNotFoundError: Le modèle spécifié n'existe pas

### ISSUE THREAD

**Issue by Fab16BSB** [DUT-Info-Montreuil/SecretarIA#16]
parser.add_argument('path_to_modele', type=str,
                        default="generation_GRU_1/GRU_epoch_20_val_loss_0.5177_val_accuracy_0.9120.h5",
                        help="Le chemin du modèle à charger depuis le dossier modele", nargs='?')

même probleme c'est la valeur est a "" pourtant j'ai mis create modele a True

**Comment by Fab16BSB** [comment]
Il serait intéressant de preciser dans le help qu'il faut mettre None si ont ne veut pas l'utiliser

**Comment by llichten29** [comment]
J'ai ajouter au help
